name: Docker

on:
  workflow_call:
  
jobs:

  docker:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.11.1  

    - name: Download a Build Artifact
      uses: actions/download-artifact@v5.0.0
      with:
    # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        name: programa

    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
      uses: docker/login-action@v3.5.0
      with:
    # Username used to log against the Docker registry
        username: lucas
    # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
          
    - name: Build and push Docker images
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: lucas/go_ci:${{github.ref_name}} #nome da imagem tem que ser em letras minúsculas
       
          



